In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /home/andreiagouveia23/.local/lib/python3.8/site-packages (1.0.3)
Requirement already satisfied: numpy>=1.13.3 in /home/andreiagouveia23/.local/lib/python3.8/site-packages (from pandas) (1.18.4)
Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3/dist-packages (from pandas) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3/dist-packages (from pandas) (2.7.3)

In [2]:
import numpy as np
import pandas as pd
from sklearn import neighbors
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import explained_variance_score
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing as pre

In [3]:
covid_data = pd.read_csv('covid_data_clean.csv')
countries_data = pd.read_csv('countries_data_clean.csv',decimal=',')

In [4]:
covid_data.head(10)

,Unnamed: 0,Country/Region,Date,Confirmed,Deaths,Recovered,Ellapsed Days
0,0,Afghanistan,2020-02-24,1,0,0,0
1,1,Afghanistan,2020-02-25,1,0,0,1
2,2,Afghanistan,2020-02-26,1,0,0,2
3,3,Afghanistan,2020-02-27,1,0,0,3
4,4,Afghanistan,2020-02-28,1,0,0,4
5,5,Afghanistan,2020-02-29,1,0,0,5
6,6,Afghanistan,2020-03-01,1,0,0,6
7,7,Afghanistan,2020-03-02,1,0,0,7
8,8,Afghanistan,2020-03-03,1,0,0,8
9,9,Afghanistan,2020-03-04,1,0,0,9

In [5]:
countries_data.head(10)

,Unnamed: 0,Country,Population,Pop. Density (per sq. mi.),Infant mortality (per 1000 births),GDP ($ per capita),Deathrate
0,0,Afghanistan,31056997,48.0,163.07,700.0,20.34
1,1,Albania,3581655,124.6,21.52,4500.0,5.22
2,2,Algeria,32930091,13.8,31.00,6000.0,4.61
3,3,Samoa,57794,290.4,9.27,8000.0,3.27
4,4,Andorra,71201,152.1,4.05,19000.0,6.25
5,5,Angola,12127071,9.7,191.19,1900.0,24.20
6,7,Antigua and Barbuda,69108,156.0,19.46,11000.0,5.37
7,8,Argentina,39921833,14.4,15.18,11200.0,7.55
8,9,Armenia,2976372,99.9,23.28,3500.0,8.23
9,11,Australia,20264082,2.6,4.69,29000.0,7.51

In [6]:
#Merge the two columns together and drop uncessary columns
merged_inner = pd.merge(left=covid_data, right=countries_data, left_on='Country/Region', right_on='Country').drop(columns=['Country', 'Date', 'Unnamed: 0_x', 'Unnamed: 0_y'])

#Drop rows with at least one missing value
merged_inner.dropna(inplace=True)

def createPrevValues(dataset, originalColumnName, commonColumnName, newColumnName):
    dataset[newColumnName] = dataset.loc[merged_inner[commonColumnName].shift(-1)==dataset[commonColumnName], originalColumnName]
    dataset[newColumnName] = dataset[newColumnName].shift()
    dataset[newColumnName].fillna(0, inplace=True)

#Get cases of previous day
createPrevValues(merged_inner, 'Confirmed', 'Country/Region', 'Prev_Confirmed')

#Get deaths of previous day
createPrevValues(merged_inner, 'Deaths', 'Country/Region', 'Prev_Deaths')

#Get Recovered of previous day
createPrevValues(merged_inner, 'Recovered', 'Country/Region', 'Prev_Recovered')


merged_inner.head(50)

,Country/Region,Confirmed,Deaths,Recovered,Ellapsed Days,Population,Pop. Density (per sq. mi.),Infant mortality (per 1000 births),GDP ($ per capita),Deathrate,Prev_Confirmed,Prev_Deaths,Prev_Recovered
0,Afghanistan,1,0,0,0,31056997,48.0,163.07,700.0,20.34,0.0,0.0,0.0
1,Afghanistan,1,0,0,1,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
2,Afghanistan,1,0,0,2,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
3,Afghanistan,1,0,0,3,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
4,Afghanistan,1,0,0,4,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
5,Afghanistan,1,0,0,5,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
6,Afghanistan,1,0,0,6,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
7,Afghanistan,1,0,0,7,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
8,Afghanistan,1,0,0,8,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
9,Afghanistan,1,0,0,9,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
10,Afghanistan,1,0,0,10,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
11,Afghanistan,1,0,0,11,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
12,Afghanistan,1,0,0,12,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
13,Afghanistan,4,0,0,13,31056997,48.0,163.07,700.0,20.34,1.0,0.0,0.0
14,Afghanistan,4,0,0,14,31056997,48.0,163.07,700.0,20.34,4.0,0.0,0.0
15,Afghanistan,5,0,0,15,31056997,48.0,163.07,700.0,20.34,4.0,0.0,0.0
16,Afghanistan,7,0,0,16,31056997,48.0,163.07,700.0,20.34,5.0,0.0,0.0
17,Afghanistan,7,0,0,17,31056997,48.0,163.07,700.0,20.34,7.0,0.0,0.0
18,Afghanistan,7,0,0,18,31056997,48.0,163.07,700.0,20.34,7.0,0.0,0.0
19,Afghanistan,11,0,0,19,31056997,48.0,163.07,700.0,20.34,7.0,0.0,0.0
20,Afghanistan,16,0,0,20,31056997,48.0,163.07,700.0,20.34,11.0,0.0,0.0
21,Afghanistan,21,0,1,21,31056997,48.0,163.07,700.0,20.34,16.0,0.0,0.0
22,Afghanistan,22,0,1,22,31056997,48.0,163.07,700.0,20.34,21.0,0.0,1.0
23,Afghanistan,22,0,1,23,31056997,48.0,163.07,700.0,20.34,22.0,0.0,1.0
24,Afghanistan,22,0,1,24,31056997,48.0,163.07,700.0,20.34,22.0,0.0,1.0
25,Afghanistan,24,0,1,25,31056997,48.0,163.07,700.0,20.34,22.0,0.0,1.0
26,Afghanistan,24,0,1,26,31056997,48.0,163.07,700.0,20.34,24.0,0.0,1.0
27,Afghanistan,40,1,1,27,31056997,48.0,163.07,700.0,20.34,24.0,0.0,1.0
28,Afghanistan,40,1,1,28,31056997,48.0,163.07,700.0,20.34,40.0,1.0,1.0
29,Afghanistan,74,1,1,29,31056997,48.0,163.07,700.0,20.34,40.0,1.0,1.0
30,Afghanistan,84,2,2,30,31056997,48.0,163.07,700.0,20.34,74.0,1.0,1.0
31,Afghanistan,94,4,2,31,31056997,48.0,163.07,700.0,20.34,84.0,2.0,2.0
32,Afghanistan,110,4,2,32,31056997,48.0,163.07,700.0,20.34,94.0,4.0,2.0
33,Afghanistan,110,4,2,33,31056997,48.0,163.07,700.0,20.34,110.0,4.0,2.0
34,Afghanistan,120,4,2,34,31056997,48.0,163.07,700.0,20.34,110.0,4.0,2.0
35,Afghanistan,170,4,2,35,31056997,48.0,163.07,700.0,20.34,120.0,4.0,2.0
36,Afghanistan,174,4,5,36,31056997,48.0,163.07,700.0,20.34,170.0,4.0,2.0
37,Afghanistan,237,4,5,37,31056997,48.0,163.07,700.0,20.34,174.0,4.0,5.0
38,Afghanistan,273,6,10,38,31056997,48.0,163.07,700.0,20.34,237.0,4.0,5.0
39,Afghanistan,281,6,10,39,31056997,48.0,163.07,700.0,20.34,273.0,6.0,10.0
40,Afghanistan,299,7,10,40,31056997,48.0,163.07,700.0,20.34,281.0,6.0,10.0
41,Afghanistan,349,7,15,41,31056997,48.0,163.07,700.0,20.34,299.0,7.0,10.0
42,Afghanistan,367,11,18,42,31056997,48.0,163.07,700.0,20.34,349.0,7.0,15.0
43,Afghanistan,423,14,18,43,31056997,48.0,163.07,700.0,20.34,367.0,11.0,18.0
44,Afghanistan,444,14,29,44,31056997,48.0,163.07,700.0,20.34,423.0,14.0,18.0
45,Afghanistan,484,15,32,45,31056997,48.0,163.07,700.0,20.34,444.0,14.0,29.0
46,Afghanistan,521,15,32,46,31056997,48.0,163.07,700.0,20.34,484.0,15.0,32.0
47,Afghanistan,555,18,32,47,31056997,48.0,163.07,700.0,20.34,521.0,15.0,32.0
48,Afghanistan,607,18,32,48,31056997,48.0,163.07,700.0,20.34,555.0,18.0,32.0
49,Afghanistan,665,21,32,49,31056997,48.0,163.07,700.0,20.34,607.0,18.0,32.0

In [7]:
#Get set with the values that the model receives
X = {'Confirmed' : merged_inner.drop(columns=[ 'Country/Region', 'Confirmed', 'Recovered']) , 'Deaths' : merged_inner.drop(columns=[ 'Country/Region', 'Deaths', 'Recovered'])}

#Values the model should predict
y = {'Confirmed' : merged_inner['Confirmed']  , 'Deaths' : merged_inner['Deaths']}

In [8]:
from sklearn import metrics


variables = ['Confirmed' , 'Deaths']
num_nei = [1 , 2 , 3 , 5 , 10 , 15 , 20 , 25]

for variable in variables:
    print("On " , variable)
    X_train, X_test, y_train, y_test = train_test_split(X[variable], y[variable], test_size=0.2, random_state=0)
    
    for num in num_nei:
        knn = neighbors.KNeighborsRegressor(num , weights='distance')

        knn.fit(X_train , y_train)

        y_pred = knn.predict(X_test)

        df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
        print(df)

        #Show Errors
        print("---------ERRORS-----------")
        print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
        print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
        print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred))) 
        print('--------')
        
print('Done')

On  Confirmed
       Actual  Predicted
6116      101      101.0
9997        4        1.0
2917      189      253.0
9731    10801    10804.0
1386        5        3.0
...       ...        ...
9057        2        4.0
6871      717      585.0
10935       1        9.0
7863      167      179.0
9650       28       27.0

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 330.12041432887355
Mean Squared Error: 3722990.7807509713
Root Mean Squared Error: 1929.505320218364
--------
       Actual     Predicted
6116      101    101.000000
9997        4      1.000000
2917      189    175.145589
9731    10801  10804.516288
1386        5      3.000000
...       ...           ...
9057        2      4.000000
6871      717    543.272977
10935       1      5.686292
7863      167    167.742880
9650       28     27.466517

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 131.0259890469051
Mean Squared Error: 1027078.7062428932
Root Mean Squared Error: 1013.4489164446786
--------
       Actual     Predicted
6116      101    103.027636
9997        4      1.522337
2917      189    158.591662
9731    10801  10799.337956
1386        5      3.000000
...       ...           ...
9057        2      4.000000
6871      717    510.294146
10935       1      5.906075
7863      167    173.565930
9650       28     27.626963

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 183.7367803210914
Mean Squared Error: 978977.5023963134
Root Mean Squared Error: 989.4329196041101
--------
       Actual     Predicted
6116      101    103.346144
9997        4      2.281048
2917      189    126.303962
9731    10801  10802.249701
1386        5      3.677506
...       ...           ...
9057        2      4.000000
6871      717    558.975772
10935       1      6.829395
7863      167    171.838703
9650       28     26.630199

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 171.83031879590402
Mean Squared Error: 841606.4249238628
Root Mean Squared Error: 917.3910970376063
--------
       Actual     Predicted
6116      101    101.779555
9997        4      2.970163
2917      189    109.612658
9731    10801  10792.922826
1386        5      5.262492
...       ...           ...
9057        2      4.491633
6871      717    507.230700
10935       1      9.015410
7863      167    158.273579
9650       28     26.958612

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 198.78807451603447
Mean Squared Error: 1019486.7750415545
Root Mean Squared Error: 1009.6963776510019
--------
       Actual     Predicted
6116      101     98.497043
9997        4      3.587153
2917      189    119.268516
9731    10801  10786.193373
1386        5      7.398313
...       ...           ...
9057        2      6.727037
6871      717    465.141022
10935       1     10.858229
7863      167    155.379683
9650       28     29.166529

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 305.33951911995825
Mean Squared Error: 3018157.521737524
Root Mean Squared Error: 1737.2845252685363
--------
       Actual     Predicted
6116      101     97.718490
9997        4      3.963245
2917      189    160.250099
9731    10801  10779.142716
1386        5      9.374766
...       ...           ...
9057        2      9.062282
6871      717    394.875060
10935       1     12.458525
7863      167    140.174484
9650       28     27.318684

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 429.6832745389348
Mean Squared Error: 6933120.250769048
Root Mean Squared Error: 2633.0818921501564
--------
       Actual     Predicted
6116      101     96.919149
9997        4      4.240067
2917      189    198.598449
9731    10801  10769.771965
1386        5     11.244340
...       ...           ...
9057        2     11.226809
6871      717    403.791449
10935       1     13.872207
7863      167    128.182523
9650       28     28.860493

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 548.1368387737645
Mean Squared Error: 12208739.61739063
Root Mean Squared Error: 3494.1006879296756
--------
On  Deaths
       Actual  Predicted
6116        8        8.0
9997        0        0.0
2917        0        0.0
9731      252      254.0
1386        0        0.0
...       ...        ...
9057        0        0.0
6871       12        8.0
10935       0        0.0
7863        0        0.0
9650        0        0.0

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 23.37203280103582
Mean Squared Error: 20755.99870522227
Root Mean Squared Error: 144.06942321402647
--------
       Actual   Predicted
6116        8    8.000000
9997        0    0.000000
2917        0    0.000000
9731      252  254.258382
1386        0    0.000000
...       ...         ...
9057        0    0.000000
6871       12    7.274116
10935       0    0.000000
7863        0    0.000000
9650        0    0.000000

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 9.790025509015573
Mean Squared Error: 6542.692658818861
Root Mean Squared Error: 80.88691277838993
--------
       Actual   Predicted
6116        8    8.000000
9997        0    0.000000
2917        0    0.000000
9731      252  253.213768
1386        0    0.000000
...       ...         ...
9057        0    0.000000
6871       12    6.766175
10935       0    0.000000
7863        0    0.227962
9650        0    0.000000

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 13.221728794048788
Mean Squared Error: 7361.781139984421
Root Mean Squared Error: 85.80082249013945
--------
       Actual   Predicted
6116        8    8.151722
9997        0    0.000000
2917        0    0.000000
9731      252  253.744141
1386        0    0.000000
...       ...         ...
9057        0    0.000000
6871       12    8.474264
10935       0    0.000000
7863        0    0.296126
9650        0    0.000000

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 13.890369609182505
Mean Squared Error: 8983.867298629277
Root Mean Squared Error: 94.78326486584685
--------
       Actual   Predicted
6116        8    8.308811
9997        0    0.000000
2917        0    0.000000
9731      252  252.097059
1386        0    0.000000
...       ...         ...
9057        0    0.000000
6871       12    9.827765
10935       0    0.000000
7863        0    0.363985
9650        0    0.000000

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 17.922735414975786
Mean Squared Error: 17075.45034217888
Root Mean Squared Error: 130.6730666288156
--------
       Actual   Predicted
6116        8    8.255511
9997        0    0.125876
2917        0    0.000000
9731      252  251.128371
1386        0    0.004356
...       ...         ...
9057        0    0.000000
6871       12    7.961838
10935       0    0.000000
7863        0    0.364538
9650        0    0.000000

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 25.152555110813857
Mean Squared Error: 32274.44814384003
Root Mean Squared Error: 179.6509063262416
--------
       Actual   Predicted
6116        8    8.391867
9997        0    0.199027
2917        0    0.074217
9731      252  250.179370
1386        0    0.037733
...       ...         ...
9057        0    0.000000
6871       12    6.753734
10935       0    0.000000
7863        0    0.326635
9650        0    0.000000

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 33.33255724767603
Mean Squared Error: 51968.354106411585
Root Mean Squared Error: 227.96568624775875
--------
       Actual   Predicted
6116        8    8.464855
9997        0    0.250803
2917        0    0.325188
9731      252  248.969362
1386        0    0.095776
...       ...         ...
9057        0    0.004122
6871       12    8.190695
10935       0    0.000000
7863        0    0.296932
9650        0    0.019530

[2317 rows x 2 columns]
---------ERRORS-----------
Mean Absolute Error: 39.01726069989806
Mean Squared Error: 68336.35004305893
Root Mean Squared Error: 261.4122224438998
--------
Done

Neural Network Regression
=======================